* Introduction
** Background
   Equalization is the process of adjusting the balance between frequency
   components within an electronic signal. An audio equalizer is an audio device
   with multiple frequency controls for adjusting sound tone quality. To be
   specific, an equalizer can be used to compensate for deficiencies in a sound
   pickup or to reduce extraneous sounds, such as noise. Besides, it can also be
   used to improve instrument clarity. For example, boosting a sounds harmonics
   gives the impression of more presence and brightness and decresasing a sounds
   harmonics gives the impression of a dull, less dazzling sound.
** Motivation
   The audio output quality of loudspeakers may not be uniform due to size,
   mechanical and cost constraints, even though they are usually designed to
   have a fairly uniform response across the frequency spectrum. Therefore,
   audio equalizer is performed to flatten this response, or to shape it
   according to listener preferences.

   In the early years, analog filters were mainly used to implement the audio
   equalizer. However, the proliferation of digital audio sources, such as the
   Internet and the USB, gives an opportunity to apply digital signal processing
   to audio signals. Actually, many advantages, which include simplification of
   design and verification, greater flexibility and reliability, and
   significantly superior sound quality, allow the creation of digital equlizer
   that can outperform its analog counterparts.
** Objective
   The objective of this project is to design and simulate an digital audio
   equalizer using Matlab. It includes both implementation and evaluation of
   the audio equalizer. 
** Report Outline
   This report mainly constists of two parts: the implementation and the
   performance analysis of an audio equalizer. In the implementation, the
   procedure of creating a Graphical User Interface (GUI) by using Matlab's App
   Designer and the construction of a FIR filter by using Matlab's DSP toolbox
   is included. Meanwhile, the performance analysis focuses on displaying the
   equalizer simulation result and elaborating the difference among outcomes
   when different filter algorithms and configurations are applied.
* Design And System Construction
  The GUI is designed by using Matlab's App Designer. As shown in the figure
  above, the equalizer is controled by 8 sliders, which represent 8 frequency
  bands and the label of each band shows its central frequency. Each buttons'
  functions:
* Algorithm And Simulation
  The FIR filter function used in this equalizer is fir2(). fir2 Uses frequency
  sampling to design filters. The function interpolates the desired frequency
  response linearly onto a dense, evenly spaced grid of length npt, which is
  default set to 512. fir2 also sets up regions of lap points around repeated
  values of f to provide steep but smooth transitions. TO obtain the filter
