* Introduction
  The Digital Signal Processor (DSP) used in this mini project is TI's TMS
  320C5515. C5515 is a 16-bit fixed-point processor and can be used for
  real-time digital signal processing applications such as Audio CODEC,
  fingerprint detection, and so on. The objective of this mini project is using
  C5515 to implement a 3-band audio equalizer with graphical control via
  embedded button, LED and LCD.
* Design And Implementation
  Matlab's 'fdatool' is used to obtain the coefficients of the FIR filter for
  the first step. To specify the passband gain and stopband attenuation,
  constrained equal ripple method needs to be choosed. As for cut-off frequency,
  some offset value can be added also to achieve a precise gain control at the
  band edge. Besides the setting of band gain, the filter's quantization
  property should be took care of too. Since C5515 is a 16-bit fixed point
  processor, the word length should be 16 bits. Q15 format determines the
  fraction length is 15 bits. 
